ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "recurrenceType" TEXT DEFAULT 'NONE';

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "daysOfWeek" INTEGER[] DEFAULT '{}';

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "startTime" TEXT;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "endTime" TEXT;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "recurrenceStart" TIMESTAMP;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "recurrenceEnd" TIMESTAMP;
