ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "requiresEnrollment" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "requiresPackage" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "directEnrollmentCost" DOUBLE PRECISION;

ALTER TABLE "Class"
ADD COLUMN IF NOT EXISTS "teacherDirectPercentage" DOUBLE PRECISION;
